// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSInnHD1Lw9JOuNM9YRaKpL9ZkUuICFV8',
    appId: '1:1061735840059:web:fc3f54b72c697249a3df1e',
    messagingSenderId: '1061735840059',
    projectId: 's5nceerlnbyaeeu5k6h7cwv1h9j36u',
    authDomain: 's5nceerlnbyaeeu5k6h7cwv1h9j36u.firebaseapp.com',
    storageBucket: 's5nceerlnbyaeeu5k6h7cwv1h9j36u.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5j4DcY5ADQbdYI1WDxowAmTC705Xf7k',
    appId: '1:1061735840059:android:5562ebdefea95033a3df1e',
    messagingSenderId: '1061735840059',
    projectId: 's5nceerlnbyaeeu5k6h7cwv1h9j36u',
    storageBucket: 's5nceerlnbyaeeu5k6h7cwv1h9j36u.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG13KHbbgu_TMmpZaVsf5JrM3OyH_9Li4',
    appId: '1:1061735840059:ios:9259bdfb187e6568a3df1e',
    messagingSenderId: '1061735840059',
    projectId: 's5nceerlnbyaeeu5k6h7cwv1h9j36u',
    storageBucket: 's5nceerlnbyaeeu5k6h7cwv1h9j36u.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
